version: '2'
services:
  web:
    container_name: web-container
    build:
      context: ./docker/web
    restart: 'no'
    volumes:
      - ./web:/var/www/html      
    depends_on:
      - mysql
    ports:
      - "${HTTP_PORT}:80"        

  mysql:
    container_name: mysql-container
    build:
      context: ./docker/mysql
    restart: 'no'
    volumes:
      - ./docker/runtime/mysql:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: ${PASSWORD}
